# Generated by Django 5.1.3 on 2024-12-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watch_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='closed',
            new_name='active',
        ),
    ]
