# Generated by Django 5.1.3 on 2024-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_closed_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
