# Generated by Django 5.1.3 on 2024-12-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_rename_watch_auction_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="proposed_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
