# Generated by Django 5.1.3 on 2024-12-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auction_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sorted_auctions",
                to="auctions.category",
            ),
        ),
    ]
